import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientStyle from "./clientStyle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientStyle clientId={process.env.clientId || "client1"}>
          {children}
        </ClientStyle>
      </body>
    </html>
  );
}
